import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const { chromium } = await import(pathToFileURL(process.env.HEDES_PLAYWRIGHT_MODULE).href);
const browser = await chromium.connectOverCDP('http://127.0.0.1:9226');
const context = browser.contexts()[0];
const page = context.pages()[0] || await context.waitForEvent('page', { timeout: 15000 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const checks = {};
try {
  await page.getByRole('button', { name: 'Settings', exact: true }).waitFor();
  checks.startup = 'passed';
  assert.equal(await page.evaluate(() => typeof window.hedesDesktop?.getSessionToken), 'function');
  const terminal = page.getByRole('textbox', { name: 'Type your command here (e.g.' });
  await terminal.fill('echo HEDES_PACKAGED_TERMINAL_OK'); await terminal.press('Enter');
  await page.getByText('HEDES_PACKAGED_TERMINAL_OK', { exact: true }).first().waitFor();
  checks.terminal = 'real PowerShell command passed';
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Appearance', exact: true }).click();
  await page.getByRole('button', { name: 'Night sky', exact: true }).click();
  const slider = page.getByRole('slider', { name: /App font size/ });
  await slider.press('Home'); await slider.press('ArrowRight');
  await page.getByRole('button', { name: 'Close settings', exact: true }).click();
  const before = await page.evaluate(() => localStorage.getItem('hedes_appearance_v1'));
  assert.ok(before);
  await page.reload();
  await page.getByRole('button', { name: 'Settings', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('hedes_appearance_v1')), before);
  checks.appearancePersistence = 'wallpaper and font survive reload';
  const wallpaper = await page.evaluate(async () => { const r = await fetch('/wallpapers/night-sky.jpg'); return { status: r.status, size: (await r.arrayBuffer()).byteLength }; });
  assert.equal(wallpaper.status, 200); assert.ok(wallpaper.size > 1000);
  checks.offlineWallpaper = wallpaper;
  const id = 'review-desktop-persistence';
  await page.evaluate(async id => {
    const post = async (route, body) => { const r = await fetch(route, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) throw new Error(route + ': ' + await r.text()); return r.json(); };
    await post('/api/local/projects', { chatId: id, title: 'Desktop review fixture', messages: [{ id: 'review-message', role: 'assistant', content: 'Disk history restored correctly.', createdAt: Date.now() }] });
    await post('/api/local/fs', { chatId: id, filePath: 'review.txt', content: 'Persisted project file' });
  }, id);
  await page.reload(); await page.getByRole('button', { name: 'Chat History', exact: true }).click();
  await page.getByText('Desktop review fixture', { exact: true }).click();
  await page.getByText('Disk history restored correctly.', { exact: true }).waitFor();
  await page.getByText('review.txt', { exact: true }).first().waitFor();
  checks.historyAndFiles = 'disk-backed chat and project reopened after reload';
  const status = await page.evaluate(async id => {
    const post = async (route, body) => { const r = await fetch(route, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!r.ok) throw new Error(await r.text()); return r.json(); };
    await post('/api/local/fs', { chatId: id, filePath: 'package.json', content: JSON.stringify({ scripts: { dev: 'node server.cjs' } }) });
    await post('/api/local/fs', { chatId: id, filePath: 'server.cjs', content: `require('node:http').createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<h1>HEDES PACKAGED PREVIEW OK</h1>')}).listen(Number(process.env.PORT),'127.0.0.1');` });
    return post('/api/local/website', { chatId: id, action: 'start' });
  }, id);
  assert.equal(status.running, true);
  await page.getByRole('button', { name: 'Preview', exact: true }).click();
  await page.getByRole('textbox', { name: 'Preview URL' }).fill(status.url);
  await page.getByRole('textbox', { name: 'Preview URL' }).press('Enter');
  await page.frameLocator('iframe').getByRole('heading', { name: 'HEDES PACKAGED PREVIEW OK' }).waitFor();
  checks.preview = 'actual child server rendered inside editable preview URL';
  await page.getByRole('button', { name: 'Open Hedes Voice', exact: true }).click();
  await page.getByRole('button', { name: 'Close voice page', exact: true }).waitFor();
  assert.equal(await page.locator('input[type=checkbox]').last().isChecked(), false);
  checks.voicePage = 'opens; cloud audio disabled by default; physical microphone untested';
  await page.getByRole('button', { name: 'Close voice page', exact: true }).click();
  await mkdir('output/playwright', { recursive: true });
  await page.screenshot({ path: 'output/playwright/review-packaged-desktop.png' });
  await page.evaluate(async id => { await fetch('/api/local/website', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ chatId: id, action: 'stop' }) }); }, id);
  assert.deepEqual(errors, []);
  const report = { checkedAt: new Date().toISOString(), checks, pageErrors: errors };
  await writeFile('output/review-desktop-results.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report));
} finally { await browser.close(); }
